language: cpp
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - ${HOME}/.cache

before_install:
  - gem install travis --no-document
  - PATH=${TRAVIS_BUILD_DIR}/scripts:$PATH
  - chmod +x ${TRAVIS_BUILD_DIR}/scripts/travis.sh
  - chmod +x ${TRAVIS_BUILD_DIR}/scripts/travis_auto_merge.sh
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

install:
  - travis.sh
  - PATH=${HOME}/.cache/deps/cmake-install:${HOME}/.cache/deps/cmake-install/bin:$PATH
  # - PATH=${HOME}/.cache/deps/llvm/bin:$PATH
  - sudo apt-get install -y clang-tidy
  - cd ${TRAVIS_BUILD_DIR}

addons:
  apt:
    packages: lcov

before_script:
  - travis login --auto
  - mkdir -p build
  - cd build

script:
  - travis_auto_merge.sh

after_script:
  - travis logout --org