language: cpp
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - ${HOME}/.cache

before_install:
  - PATH=${TRAVIS_BUILD_DIR}/scripts:$PATH
  - chmod +x ${TRAVIS_BUILD_DIR}/scripts/travis.sh

install:
  - ./travis.sh
  # - mkdir -p ${HOME}/.cache
  # - DEPS_DIR="${HOME}/.cache/deps"
  # - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  # - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.4-Linux-x86_64.tar.gz
  # - echo "126cc8356907913787d4ff35237ae1854c09b927a35dbe5270dd571ae224bdd3 *cmake-3.17.4-Linux-x86_64.tar.gz" > cmake_sha256.txt
  # - sha256sum -c cmake_sha256.txt
  # - tar -xvf cmake-3.17.4-Linux-x86_64.tar.gz > /dev/null
  # - mv cmake-3.17.4-Linux-x86_64 cmake-install
  # - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # - cd ${TRAVIS_BUILD_DIR}

addons:
  apt:
    packages: lcov

before_script:
  - mkdir -p build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug -- -j $(nproc)
  - ctest -j $(nproc) --output-on-failure

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.info