language: cpp
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - ${HOME}/.cache

before_install:
  - PATH=${TRAVIS_BUILD_DIR}/scripts:$PATH
  - chmod +x ${TRAVIS_BUILD_DIR}/scripts/travis.sh

install:
  - travis.sh
  - PATH=${HOME}/.cache/deps/cmake-install:${HOME}/.cache/deps/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

addons:
  apt:
    packages: lcov

before_script:
  - mkdir -p build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug -- -j $(nproc)
  - ctest -j $(nproc) --output-on-failure

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.info