#include "RayTracer/RayTracer.h"
#include "RuntimeReflection/Recorder.h"
#include "RuntimeReflection/GeneratedMeta.h"


DUCKVIL_RUNTIME_REFLECTION_RECORD(1)
{
using namespace Duckvil::RuntimeReflection;
using namespace Duckvil;
DUCKVIL_RESOURCE(type_t) _type;
DUCKVIL_RESOURCE(property_t) _property;
DUCKVIL_RESOURCE(constructor_t) _constructor;
DUCKVIL_RESOURCE(destructor_t) _destructor;
DUCKVIL_RESOURCE(function_t) _function;
DUCKVIL_RESOURCE(enum_t) _enum;
DUCKVIL_RESOURCE(enum_element_t) _enumElement;
DUCKVIL_RESOURCE(ntype_t) _ntype;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_type_t> _recordedTypes;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_ntype_t> _recordedNTypes;
std::vector<const char*> _namespaces;
{
_namespaces.push_back("Duckvil");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
{
_namespaces.push_back("Graphics");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
{
_namespaces.push_back("RayTracer");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.push_back("Transform");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
using namespace Duckvil::Graphics::RayTracer;
_type = record_type<Duckvil::Graphics::RayTracer::Transform>(_data, "Transform");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "Graphics");
record_namespace(_data, _type, "RayTracer");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 1);
_property = record_property<glm::mat4>(_data, _type, offsetof(Duckvil::Graphics::RayTracer::Transform, m_mat4ForwardTransform), "m_mat4ForwardTransform");
_property = record_property<glm::mat4>(_data, _type, offsetof(Duckvil::Graphics::RayTracer::Transform, m_mat4BackwardTransform), "m_mat4BackwardTransform");
_property = record_property<glm::mat3>(_data, _type, offsetof(Duckvil::Graphics::RayTracer::Transform, m_mat3LinearTransform), "m_mat3LinearTransform");
_namespaces.pop_back();
_namespaces.push_back("RayTracer");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_type = record_type<Duckvil::Graphics::RayTracer::RayTracer>(_data, "RayTracer");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "Graphics");
record_namespace(_data, _type, "RayTracer");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 1);
record_inheritance<ISystem>(_data, _type, __protection::__protection_public);
record_inheritance<Editor::Widget>(_data, _type, __protection::__protection_public);
_constructor = record_constructor<Duckvil::Graphics::RayTracer::RayTracer>(_data, _type);
_constructor = record_constructor<Duckvil::Graphics::RayTracer::RayTracer, const Memory::FreeList&, Event::Pool<Event::mode::buffered>*>(_data, _type);
record_meta(_data, _type, _constructor, 1, "Window", true);
_destructor = record_destructor<Duckvil::Graphics::RayTracer::RayTracer>(_data, _type);
_function = record_function<Duckvil::Graphics::RayTracer::RayTracer, bool>(_data, _type, &Duckvil::Graphics::RayTracer::RayTracer::Init, "Init");
_function = record_function<Duckvil::Graphics::RayTracer::RayTracer, void, double>(_data, _type, &Duckvil::Graphics::RayTracer::RayTracer::Update, "Update");
_function = record_function<Duckvil::Graphics::RayTracer::RayTracer, void, void*>(_data, _type, &Duckvil::Graphics::RayTracer::RayTracer::InitEditor, "InitEditor");
_function = record_function<Duckvil::Graphics::RayTracer::RayTracer, void>(_data, _type, &Duckvil::Graphics::RayTracer::RayTracer::OnDraw, "OnDraw");
_function = record_function<void*, void*>(_data, _type, &Duckvil::Graphics::RayTracer::RayTracer::Cast, "Cast");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_function = record_function<Duckvil::Graphics::RayTracer::RayTracer, void, Duckvil::RuntimeSerializer::ISerializer*>(_data, _type, &Duckvil::Graphics::RayTracer::RayTracer::Serialize, "Serialize");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_namespaces.pop_back();
_namespaces.pop_back();
}
_namespaces.pop_back();
}
_namespaces.pop_back();
}
return duckvil_recorded_types_create(_data._pMemoryInterface, _data._pAllocator, _recordedTypes, "RayTracer/RayTracer.h", 1);
}
#ifdef DUCKVIL_RUNTIME_COMPILE
DUCKVIL_EXPORT uint32_t duckvil_get_recorder_index()
{
return 1;
}
#endif
