#include "Graphics/TransformComponent.h"
#include "RuntimeReflection/Recorder.h"
#include "RuntimeReflection/GeneratedMeta.h"


DUCKVIL_RUNTIME_REFLECTION_RECORD(4)
{
using namespace Duckvil::RuntimeReflection;
using namespace Duckvil;
DUCKVIL_RESOURCE(type_t) _type;
DUCKVIL_RESOURCE(property_t) _property;
DUCKVIL_RESOURCE(constructor_t) _constructor;
DUCKVIL_RESOURCE(destructor_t) _destructor;
DUCKVIL_RESOURCE(function_t) _function;
DUCKVIL_RESOURCE(enum_t) _enum;
DUCKVIL_RESOURCE(enum_element_t) _enumElement;
DUCKVIL_RESOURCE(ntype_t) _ntype;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_type_t> _recordedTypes;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_ntype_t> _recordedNTypes;
std::vector<const char*> _namespaces;
{
_namespaces.push_back("Duckvil");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
{
_namespaces.push_back("Graphics");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.push_back("TransformComponent");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
using namespace Duckvil::Graphics;
_type = record_type<Duckvil::Graphics::TransformComponent>(_data, "TransformComponent");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "Graphics");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 4);
_property = record_property<glm::vec3>(_data, _type, offsetof(Duckvil::Graphics::TransformComponent, m_position), "m_position");
_property = record_property<glm::quat>(_data, _type, offsetof(Duckvil::Graphics::TransformComponent, m_rotation), "m_rotation");
_property = record_property<glm::vec3>(_data, _type, offsetof(Duckvil::Graphics::TransformComponent, m_scale), "m_scale");
_function = record_function<void, void*>(_data, _type, &Duckvil::Graphics::TransformComponent::InitEditor, "InitEditor");
_function = record_function<void, char const*, glm::vec3*>(_data, _type, &Duckvil::Graphics::TransformComponent::Draw, "Draw");
_function = record_function<void, char const*, glm::quat*>(_data, _type, &Duckvil::Graphics::TransformComponent::Draw, "Draw");
_function = record_function<void*, void*>(_data, _type, &Duckvil::Graphics::TransformComponent::Cast, "Cast");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_function = record_function<Duckvil::Graphics::TransformComponent, void, Duckvil::RuntimeSerializer::ISerializer*>(_data, _type, &Duckvil::Graphics::TransformComponent::Serialize, "Serialize");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_namespaces.pop_back();
_namespaces.pop_back();
}
_namespaces.pop_back();
}
return duckvil_recorded_types_create(_data._pMemoryInterface, _data._pAllocator, _recordedTypes, "Graphics/TransformComponent.h", 4);
}
#ifdef DUCKVIL_RUNTIME_COMPILE
DUCKVIL_EXPORT uint32_t duckvil_get_recorder_index()
{
return 4;
}
#endif
