#include "Editor/Widgets/EntityInspectorWidget.h"
#include "RuntimeReflection/Recorder.h"
#include "RuntimeReflection/GeneratedMeta.h"


DUCKVIL_RUNTIME_REFLECTION_RECORD(11)
{
using namespace Duckvil::RuntimeReflection;
using namespace Duckvil;
DUCKVIL_RESOURCE(type_t) _type;
DUCKVIL_RESOURCE(property_t) _property;
DUCKVIL_RESOURCE(constructor_t) _constructor;
DUCKVIL_RESOURCE(destructor_t) _destructor;
DUCKVIL_RESOURCE(function_t) _function;
DUCKVIL_RESOURCE(enum_t) _enum;
DUCKVIL_RESOURCE(enum_element_t) _enumElement;
DUCKVIL_RESOURCE(ntype_t) _ntype;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_type_t> _recordedTypes;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_ntype_t> _recordedNTypes;
std::vector<const char*> _namespaces;
{
_namespaces.push_back("Duckvil");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
{
_namespaces.push_back("Editor");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.push_back("EntityInspectorWidget");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
using namespace Duckvil::Editor;
_type = record_type<Duckvil::Editor::EntityInspectorWidget>(_data, "EntityInspectorWidget");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "Editor");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 11);
record_meta(_data, _type, ReflectionFlags_AutoEventsAdding, true);
record_inheritance<Widget>(_data, _type, __protection::__protection_public);
_constructor = record_constructor<Duckvil::Editor::EntityInspectorWidget, Memory::FreeList const&, Event::Pool<Event::mode::immediate>*, ECS::EntityFactory*, Event::Pool<Event::mode::immediate>*>(_data, _type);
record_meta(_data, _type, _constructor, 1, "Editor", true);
record_meta(_data, _type, _constructor, 3, "Engine", true);
_destructor = record_destructor<Duckvil::Editor::EntityInspectorWidget>(_data, _type);
_function = record_function<Duckvil::Editor::EntityInspectorWidget, void, void*>(_data, _type, &Duckvil::Editor::EntityInspectorWidget::InitEditor, "InitEditor");
_function = record_function<Duckvil::Editor::EntityInspectorWidget, void>(_data, _type, &Duckvil::Editor::EntityInspectorWidget::OnDraw, "OnDraw");
_function = record_function<Duckvil::Editor::EntityInspectorWidget, void, EntitySelectedEvent const&>(_data, _type, &Duckvil::Editor::EntityInspectorWidget::OnEvent, "OnEvent");
_function = record_function<Duckvil::Editor::EntityInspectorWidget, void, HotReloader::SwapEvent const&>(_data, _type, &Duckvil::Editor::EntityInspectorWidget::OnEvent, "OnEvent");
_function = record_function<Duckvil::Editor::EntityInspectorWidget, void, ProjectManager::OnLoadEvent const&>(_data, _type, &Duckvil::Editor::EntityInspectorWidget::OnEvent, "OnEvent");
_function = record_function<void*, void*>(_data, _type, &Duckvil::Editor::EntityInspectorWidget::Cast, "Cast");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_function = record_function<Duckvil::Editor::EntityInspectorWidget, void, Duckvil::RuntimeSerializer::ISerializer*>(_data, _type, &Duckvil::Editor::EntityInspectorWidget::Serialize, "Serialize");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_namespaces.pop_back();
_namespaces.push_back("Function");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.pop_back();
_namespaces.push_back("Component");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.pop_back();
_namespaces.push_back("Script");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.pop_back();
_namespaces.push_back("ExternalModule");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.pop_back();
_namespaces.pop_back();
}
_namespaces.pop_back();
}
return duckvil_recorded_types_create(_data._pMemoryInterface, _data._pAllocator, _recordedTypes, "Editor/Widgets/EntityInspectorWidget.h", 11);
}
#ifdef DUCKVIL_RUNTIME_COMPILE
DUCKVIL_EXPORT uint32_t duckvil_get_recorder_index()
{
return 11;
}
#endif
