#include "Editor/Widgets/ViewportWidget.h"
#include "RuntimeReflection/Recorder.h"
#include "RuntimeReflection/GeneratedMeta.h"

DUCKVIL_RUNTIME_REFLECTION_RECORD(16)
{
using namespace Duckvil::RuntimeReflection;
using namespace Duckvil;
DUCKVIL_RESOURCE(type_t) _type;
DUCKVIL_RESOURCE(property_t) _property;
DUCKVIL_RESOURCE(constructor_t) _constructor;
DUCKVIL_RESOURCE(destructor_t) _destructor;
DUCKVIL_RESOURCE(function_t) _function;
DUCKVIL_RESOURCE(enum_t) _enum;
DUCKVIL_RESOURCE(enum_element_t) _enumElement;
DUCKVIL_RESOURCE(ntype_t) _ntype;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_type_t> _recordedTypes;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_ntype_t> _recordedNTypes;
std::vector<const char*> _namespaces;
{
_namespaces.push_back("Duckvil");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
{
_namespaces.push_back("Editor");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.push_back("ViewportWidget");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
using namespace Duckvil::Editor;
_type = record_type<Duckvil::Editor::ViewportWidget>(_data, "ViewportWidget");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "Editor");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 16);
record_meta(_data, _type, Duckvil::ReflectionFlags::ReflectionFlags_UserSystem, true);
record_inheritance<Widget>(_data, _type, __protection::__protection_public);
record_inheritance<ISystem>(_data, _type, __protection::__protection_public);
record_inheritance<Network::NetworkSystem>(_data, _type, __protection::__protection_public);
_constructor = record_constructor<Duckvil::Editor::ViewportWidget>(_data, _type);
_constructor = record_constructor<Duckvil::Editor::ViewportWidget, const Memory::FreeList&, Event::Pool<Event::mode::buffered>*, Network::IServer*, Network::IClient*>(_data, _type);
record_meta(_data, _type, _constructor, 1, "Window", true);
_destructor = record_destructor<Duckvil::Editor::ViewportWidget>(_data, _type);
_function = record_function<Duckvil::Editor::ViewportWidget, bool>(_data, _type, &Duckvil::Editor::ViewportWidget::Init, "Init");
_function = record_function<Duckvil::Editor::ViewportWidget, void, double>(_data, _type, &Duckvil::Editor::ViewportWidget::Update, "Update");
_function = record_function<Duckvil::Editor::ViewportWidget, void, void*>(_data, _type, &Duckvil::Editor::ViewportWidget::InitEditor, "InitEditor");
_function = record_function<Duckvil::Editor::ViewportWidget, void>(_data, _type, &Duckvil::Editor::ViewportWidget::OnDraw, "OnDraw");
_function = record_function<Duckvil::Editor::ViewportWidget, void, Graphics::Renderer::renderer_ftable*, Graphics::Renderer::renderer_data*>(_data, _type, &Duckvil::Editor::ViewportWidget::SetRenderer, "SetRenderer");
_function = record_function<Duckvil::Editor::ViewportWidget, void, flecs::world*>(_data, _type, &Duckvil::Editor::ViewportWidget::SetECS, "SetECS");
_function = record_function<Duckvil::Editor::ViewportWidget, void, Duckvil::Network::IConnection::Owner>(_data, _type, &Duckvil::Editor::ViewportWidget::SetOwner, "SetOwner");
_function = record_function<Duckvil::Editor::ViewportWidget, bool, const Duckvil::Network::Message&, std::shared_ptr<Duckvil::Network::IConnection>>(_data, _type, &Duckvil::Editor::ViewportWidget::OnMessage, "OnMessage");
_function = record_function<void*, void*>(_data, _type, &Duckvil::Editor::ViewportWidget::Cast, "Cast");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_function = record_function<Duckvil::Editor::ViewportWidget, void, Duckvil::RuntimeSerializer::ISerializer*>(_data, _type, &Duckvil::Editor::ViewportWidget::Serialize, "Serialize");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_namespaces.pop_back();
_enum = record_enum<Duckvil::Editor::ViewportWidget::NetworkCommands>(_data, _ntype, "NetworkCommands");
_enumElement = record_enum_element(_data, _ntype, _enum, Duckvil::Editor::ViewportWidget::NetworkCommands::PlayerMovement, "PlayerMovement");
_enumElement = record_enum_element(_data, _ntype, _enum, Duckvil::Editor::ViewportWidget::NetworkCommands::AddPlayer, "AddPlayer");
_namespaces.push_back("NetworkComponent");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_type = record_type<Duckvil::Editor::ViewportWidget::NetworkComponent>(_data, "NetworkComponent");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "Editor");
record_namespace(_data, _type, "ViewportWidget");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 16);
_property = record_property<uint32_t>(_data, _type, offsetof(Duckvil::Editor::ViewportWidget::NetworkComponent, m_uiID), "m_uiID");
_namespaces.pop_back();
_namespaces.pop_back();
}
_namespaces.pop_back();
}
return duckvil_recorded_types_create(_data._pMemoryInterface, _data._pAllocator, _recordedTypes, "Editor/Widgets/ViewportWidget.h", 16);
}
#ifdef DUCKVIL_RUNTIME_COMPILE
DUCKVIL_EXPORT uint32_t duckvil_get_recorder_index()
{
return 16;
}
#endif
