#include "TestSystem/TestSystem.h"
#include "RuntimeReflection/Recorder.h"
#include "RuntimeReflection/GeneratedMeta.h"

DUCKVIL_RUNTIME_REFLECTION_RECORD(0)
{
using namespace Duckvil::RuntimeReflection;
using namespace Duckvil;
DUCKVIL_RESOURCE(type_t) _type;
DUCKVIL_RESOURCE(property_t) _property;
DUCKVIL_RESOURCE(constructor_t) _constructor;
DUCKVIL_RESOURCE(destructor_t) _destructor;
DUCKVIL_RESOURCE(function_t) _function;
DUCKVIL_RESOURCE(enum_t) _enum;
DUCKVIL_RESOURCE(enum_element_t) _enumElement;
DUCKVIL_RESOURCE(ntype_t) _ntype;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_type_t> _recordedTypes;
std::vector<Duckvil::RuntimeReflection::__duckvil_resource_ntype_t> _recordedNTypes;
std::vector<const char*> _namespaces;
{
_namespaces.push_back("Duckvil");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
{
_namespaces.push_back("LOL");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_namespaces.push_back("Test");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
using namespace Duckvil::LOL;
_type = record_type<Duckvil::LOL::Test>(_data, "Test");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "LOL");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 0);
record_meta(_data, _type, ReflectionFlags::ReflectionFlags_UserSystem, true);
record_inheritance<ISystem>(_data, _type, __protection::__protection_public);
record_inheritance<Editor::Widget>(_data, _type, __protection::__protection_public);
_constructor = record_constructor<Duckvil::LOL::Test>(_data, _type);
_constructor = record_constructor<Duckvil::LOL::Test, const Memory::FreeList&>(_data, _type);
_destructor = record_destructor<Duckvil::LOL::Test>(_data, _type);
_function = record_function<Duckvil::LOL::Test, bool>(_data, _type, &Duckvil::LOL::Test::Init, "Init");
_function = record_function<Duckvil::LOL::Test, void, double>(_data, _type, &Duckvil::LOL::Test::Update, "Update");
_function = record_function<Duckvil::LOL::Test, void, void*>(_data, _type, &Duckvil::LOL::Test::InitEditor, "InitEditor");
_function = record_function<Duckvil::LOL::Test, void>(_data, _type, &Duckvil::LOL::Test::OnDraw, "OnDraw");
_function = record_function<Duckvil::LOL::Test, int, int, int, int>(_data, _type, &Duckvil::LOL::Test::some_func2, "some_func2");
record_meta(_data, _type, _function, "NamedArguments", true);
_function = record_function<void*, void*>(_data, _type, &Duckvil::LOL::Test::Cast, "Cast");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_function = record_function<Duckvil::LOL::Test, void, Duckvil::RuntimeSerializer::ISerializer*>(_data, _type, &Duckvil::LOL::Test::Serialize, "Serialize");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_namespaces.pop_back();
_namespaces.push_back("test");
_ntype = record_type(_data, _namespaces);
_recordedNTypes.push_back(_ntype);
_type = record_type<Duckvil::LOL::Test::test>(_data, "test");
_recordedTypes.push_back(_type);
record_namespace(_data, _type, "Duckvil");
record_namespace(_data, _type, "LOL");
record_namespace(_data, _type, "Test");
record_meta(_data, _type, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_RecorderID, 0);
_function = record_function<Duckvil::LOL::Test::test, void, int, int, int>(_data, _type, &Duckvil::LOL::Test::test::some_func, "some_func");
record_meta(_data, _type, _function, "NamedArguments", true);
_function = record_function<void*, void*>(_data, _type, &Duckvil::LOL::Test::test::Cast, "Cast");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_function = record_function<Duckvil::LOL::Test::test, void, Duckvil::RuntimeSerializer::ISerializer*>(_data, _type, &Duckvil::LOL::Test::test::Serialize, "Serialize");
record_meta(_data, _type, _function, Duckvil::RuntimeReflection::GeneratedMeta::GeneratedMeta_AutoGenerated, true);
_namespaces.pop_back();
_namespaces.pop_back();
}
_namespaces.pop_back();
}
return duckvil_recorded_types_create(_data._pMemoryInterface, _data._pAllocator, _recordedTypes, "TestSystem/TestSystem.h", 0);
}
#ifdef DUCKVIL_RUNTIME_COMPILE
DUCKVIL_EXPORT uint32_t duckvil_get_recorder_index()
{
return 0;
}
#endif
